myMovieReviews/MovieReviewSite/MovieReviewSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('reviews/', include('reviews.urls'))
]

myMovieReviews/MovieReviewSite/reviews/urls.py
from django.urls import path 
from . import views

app_name = 'reviews'

urlpatterns = [
	path('', view = views.review_list, name = 'list'),
	path('<int:pk>/', view = views.review_detail, name = 'detail'),
	path('create/', view = views.review_create, name = 'create'),
	path('<int:pk>/update', view = views.review_update, name = 'update'),
	path('<int:pk>/delete', view = views.review_delete, name = 'delete'),
]

myMovieReviews/MovieReviewSite/reviews/models.py
from django.db import models

class Review(models.Model):
	title = models.CharField(verbose_name='제목', max_length=50)
	releaseYear = models.CharField(verbose_name='개봉년도', max_length=10)
	director = models.CharField(verbose_name='감독', max_length=20)
	actor = models.CharField(verbose_name='주연', max_length=50)
	genre = models.CharField(verbose_name='장르', max_length=20)
	rating  = models.FloatField(verbose_name='별점')
	runningTime = models.IntegerField(verbose_name='러닝타임')
	content = models.TextField(verbose_name='리뷰내용')

	def __str__(self):
		return self.title

myMovieReviews/MovieReviewSite/reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = '__all__'

myMovieReviews/MovieReviewSite/reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review
from .forms import ReviewForm

def review_list(request):
	reviews = Review.objects.all()
	ctx = {'reviews' : reviews}
	return render(request, template_name = 'list.html', context = ctx)

def review_detail(request, pk):
	review = Review.objects.get(id=pk)
	ctx = {'review' : review}
	return render(request, template_name = 'detail.html', context = ctx)

def review_create(request):
	if request.method == 'POST':
		form = ReviewForm(request.POST) 
		if form.is_valid():
			form = form.save()
			return redirect('reviews:list')
	else:
		form = ReviewForm() 
		ctx = {'form' : form}
		return render(request, template_name = 'review_form.html', context = ctx)

def review_update(request, pk):
	review = get_object_or_404(Review, id=pk)

	if request.method == 'POST':
		form = ReviewForm(request.POST, instance = review)
		if form.is_valid():
			review = form.save()
			return redirect('reviews:detail', pk)
	else :
		form = ReviewForm(instance = review)
		ctx = {'form' : form}
		return render(request, template_name = 'review_form.html', context = ctx)

def review_delete(request, pk):
    review = get_object_or_404(Review, id=pk)
    review.delete()
    return redirect('reviews:list')

myMovieReviews/MovieReviewSite/reviews/templates/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>리뷰 상세</title>
</head>

<body>
	<div>
		<a href="{% url 'reviews:list' %}">my Movie reviews</a> <br />
		<hr>
		<h2>{{review.title}}</h2>
		<h4>개봉년도 {{review.releaseYear}}</h4>
		<h4>감독 {{review.director}}</h4>
		<h4>주연 {{review.actor}}</h4>
		<h4>장르 {{review.genre}}</h4>
		<h4>별점 {{review.rating}}</h4>
		<h4>러닝타임 {{review.runningTime}}</h4>
		<p>{{review.content}}</p>
		<br />
		<a href="{% url 'reviews:update' review.id %}">수정</a>
		<a href="{% url 'reviews:delete' review.id %}">삭제</a>
	</div>
</body>

</html>

myMovieReviews/MovieReviewSite/reviews/templates/list.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>리뷰 목록</title>
</head>

<body>
	{% for review in reviews %}
	<div>
		<a href="{% url 'reviews:detail' review.id %}">
			<h2>{{review.title}}</h2>
		</a>
		<h4>개봉년도 {{review.releaseYear}}</h4>
		<h4>장르 {{review.genre}}</h4>
		<h4>별점 {{review.rating}}</h4>
		<a href="{% url 'reviews:create' %}">리뷰작성</a>
	</div>
	{% endfor %}
</body>

</html>

myMovieReviews/MovieReviewSite/reviews/templates/review_form.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>리뷰 작성</title>
</head>

<body>
	<form action="" method="POST">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<input type="submit" value="저장" class="submit_review" />
	</form>
</body>

</html>