SWIDEA_SITE/swidea/urls.py
from django.urls import path
from . import views

app_name = "swidea"

urlpatterns = [
	path('', views.idea_list, name = 'idea_list'), # 앱 swidea의 urls 파일과 연결
	path('plus_interest/', views.plus_interest, name="plus_interest"),
    path('minus_interest/', views.minus_interest, name="minus_interest"),
	
	path('<int:pk>/', views.idea_detail, name = 'idea_detail'),
	path('create/', view = views.idea_create, name = 'idea_create'),
	path('<int:pk>/update', view = views.idea_update, name = 'idea_update'),
	path('<int:pk>/delete', view = views.idea_delete, name = 'idea_delete'),

	path('devtool', view = views.devtool_list, name = 'devtool_list'),
	path('devtool/create/', view = views.devtool_create, name = 'devtool_create'),
	path('devtool/<int:pk>/', view = views.devtool_detail, name = 'devtool_detail'),
	path('devtool/<int:pk>/update', view = views.devtool_update, name = 'devtool_update'),
	path('devtool/<int:pk>/delete', view = views.devtool_delete, name = 'devtool_delete'),
]

SWIDEA_SITE/swidea/models.py
from django.db import models

class Devtool(models.Model):
	name = models.CharField(verbose_name='이름', max_length=20)
	kind = models.CharField(verbose_name='종류', max_length=50)
	description = models.TextField(verbose_name='개발툴설명')

	def __str__(self):
		return self.name

class Idea(models.Model):
	title = models.CharField(verbose_name='아이디어명', max_length=20)
	image = models.ImageField(verbose_name='대표사진', upload_to="image", null=True, blank=True)
	content = models.TextField(verbose_name='아이디어설명')
	interest = models.IntegerField(verbose_name='아이디어관심도')
	# 개발툴 리스트 중에서 항목선택
	devtool = models.ForeignKey(Devtool, on_delete=models.CASCADE, verbose_name='예상개발툴')
	
	def __str__(self):
		return self.title

SWIDEA_SITE/swidea/forms.py
from django import forms
from .models import *

class IdeaForm(forms.ModelForm):
	class Meta:
		model = Idea
		fields = '__all__'

class DevtoolForm(forms.ModelForm):
	class Meta:
		model = Devtool
		fields = '__all__'

SWIDEA_SITE/swidea/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from .models import *
from .forms import *

def idea_list(request):
	ideas = Idea.objects.all()
	ctx = {'ideas' : ideas}
	return render(request, template_name = 'list.html', context = ctx)


def plus_interest(request):
    pk = request.POST.get('pk', None)
    idea = get_object_or_404(Idea, pk=pk)
    idea.interest += 1
    idea.save()
    context = {'plus_interest': idea.interest}
    return JsonResponse(context)

def minus_interest(request):
    pk = request.POST.get('pk', None)
    idea = get_object_or_404(Idea, pk=pk)
    idea.interest -= 1
    idea.save()
    context = {'minus_interest': idea.interest}
    return JsonResponse(context)



def idea_detail(request, pk):
	idea = Idea.objects.get(id=pk)
	devtool = idea.devtool # 외래키로 지정한 Devtool 가져옴

	ctx = {'idea' : idea, 'devtool' : devtool}
	return render(request, template_name = 'detail.html', context = ctx)

def idea_create(request):
	if request.method == 'POST':
		form = IdeaForm(request.POST, request.FILES) 
		if form.is_valid():
			form = form.save()
			return redirect('swidea:idea_detail', pk=form.pk)
	else:
		form = IdeaForm() 
		ctx = {'form' : form}
		return render(request, template_name = 'idea_form_register.html', context = ctx)

def idea_update(request, pk):
	idea = get_object_or_404(Idea, id=pk)

	if request.method == 'POST':
		form = IdeaForm(request.POST, request.FILES, instance = idea)
		if form.is_valid():
			idea = form.save()
			return redirect('swidea:idea_detail', pk)
	else :
		form = IdeaForm(instance = idea)
		ctx = {'form' : form}
		return render(request, template_name = 'idea_form_update.html', context = ctx)

def idea_delete(request, pk):
    idea = get_object_or_404(Idea, id=pk)
    idea.delete()
    return redirect('swidea:idea_list')


def devtool_list(request):
	devtools = Devtool.objects.all()
	ctx = {'devtools' : devtools}
	return render(request, template_name = 'devtool_list.html', context = ctx)

def devtool_create(request):
	if request.method == 'POST':
		form = DevtoolForm(request.POST) 
		if form.is_valid():
			form = form.save()
			return redirect('swidea:devtool_detail', pk=form.pk)
	else:
		form = DevtoolForm() 
		ctx = {'form' : form}
		return render(request, template_name = 'devtool_register.html', context = ctx)

def devtool_detail(request, pk):
	devtool = Devtool.objects.get(id=pk)
	ideas = Idea.objects.filter(devtool=pk)
	# devool detail 페이지와 동일한 pk를 가진것들을 Idea객체 중에 찾아서 반환

	ctx = {'devtool' : devtool, 'ideas' : ideas}
	return render(request, template_name = 'devtool_detail.html', context = ctx)

def devtool_update(request, pk):
	devtool = get_object_or_404(Devtool, id=pk)

	if request.method == 'POST':
		form = DevtoolForm(request.POST, instance = devtool)
		if form.is_valid():
			devtool = form.save()
			print('pk:', pk)
			return redirect('swidea:devtool_detail', pk)
	else :
		form = DevtoolForm(instance = devtool)
		ctx = {'form' : form}
		return render(request, template_name = 'devtool_update.html', context = ctx)

def devtool_delete(request, pk):
    devtool = get_object_or_404(Devtool, id=pk)
    devtool.delete()
    return redirect('swidea:devtool_list')

SWIDEA_SITE/swidea/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css-reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

	<script src="https://kit.fontawesome.com/7d6a50a6b2.js" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<title>SWIDEA</title>
</head>

<body>
	<nav class="menu">
		<a href="{% url 'swidea:idea_list' %}">My SW Idea Manage</a>

		<a href="{% url 'swidea:idea_create' %}">아이디어 등록</a>
		<a href="{% url 'swidea:idea_list' %}">아이디어 관리</a>
		<a href="{% url 'swidea:devtool_create' %}">개발툴 등록</a>
		<a href="{% url 'swidea:devtool_list' %}">개발툴 관리</a>
	</nav>
	<br />

	<!-- 기본 템플릿 안에 삽입될 내용 Start -->
	{% block content %}
	{% endblock %}
	<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>

</html>

SWIDEA_SITE/swidea/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Idea Detail</h1>

{% if idea.image %}
<img src="{{idea.image.url}}" height="220" width="160">
{% else %}
<img src="https://picsum.photos/seed/{{idea.id}}/160/220?">
{% endif %}

<h2>{{idea.title}}</h2>

<h4>1) 아이디어 관심도:</h4>
{{idea.interest}}
<h4>2) 예상 개발 툴:</h4>
<a href="{% url 'swidea:devtool_detail' devtool.id%}">{{idea.devtool}}</a>

<h4>3) 아이디어 설명:</h4>
{{idea.content}}
<br />
<br />

<button type="button" class="btn btn-danger"><a href="{% url 'swidea:idea_delete' idea.id %}">삭제</a></button>
<button type="button" class="btn btn-primary"><a href="{% url 'swidea:idea_list' %}">목록</a></button>
<button type="button" class="btn btn-info"><a href="{% url 'swidea:idea_update' idea.id %}">수정</a></button>

{% endblock %}

SWIDEA_SITE/swidea/templates/devtool_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>DevTool Detail</h1>
<p>개발자툴 디테일 페이지</p>

<h2>{{devtool.name}}</h2>
<h4>{{devtool.kind}}</h4>
<h4>{{devtool.description}}</h4>
<hr>
<h4>만들 수 있는 SW 목록</h4>

{% for idea in ideas %}
<a href="{% url 'swidea:idea_detail' idea.id%}">{{ idea.title }}</a>

<br />
{% endfor %}
<br />
<br />

<button type="button" class="btn btn-danger"><a href="{% url 'swidea:devtool_delete' devtool.id %}">삭제</a></button>
<button type="button" class="btn btn-primary"><a href="{% url 'swidea:devtool_list' %}">목록</a></button>
<button type="button" class="btn btn-info"><a href="{% url 'swidea:devtool_update' devtool.id %}">수정</a></button>

{% endblock %}

SWIDEA_SITE/swidea/templates/devtool_list.html
{% extends 'base.html' %}

{% block content %}
<h2>DevTool List</h2>
<p>데크툴 목록 페이지</p>
<br />

<div class="devtools">
	{% for devtool in devtools %}
	<h2><a href="{% url 'swidea:devtool_detail' devtool.id %}">{{devtool.name}}</a></h2>
	<hr>
	{{devtool.kind}}
	<br />
	{{devtool.description}}

	<br />
	<br />
	{% endfor%}
</div>

{% endblock %}

SWIDEA_SITE/swidea/templates/devtool_register.html
{% extends 'base.html' %}

{% block content %}
<h1>DevTool Register</h1>
<p>개발툴 등록페이지입니다.</p>
<hr />
<form action="" method="POST">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit" class="submit_devtool" />
</form>

{% endblock %}

SWIDEA_SITE/swidea/templates/devtool_update.html
{% extends 'base.html' %}

{% block content %}
<h1>DevTool Detail Update</h1>
<p>개발툴 세부수정 페이지</p>
<hr />
<form action="" method="POST">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit" class="submit_devtool" />
</form>

{% endblock %}

SWIDEA_SITE/swidea/templates/idea_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Idea Register</h1>
<p>아이디어 등록페이지입니다.</p>
<hr />
<form action="" method="POST">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit" class="submit_review" />
</form>

{% endblock %}

SWIDEA_SITE/swidea/templates/idea_form_register.html
{% extends 'base.html' %}

{% block content %}
<h1>Idea Register</h1>
<p>아이디어 등록페이지입니다.</p>
<hr />
<form action="" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit" class="submit_idea" />
</form>

{% endblock %}

SWIDEA_SITE/swidea/templates/idea_form_update.html
{% extends 'base.html' %}

{% block content %}
<h1>Idea Detail Update</h1>
<p>아이디어 세부수정 페이지</p>
<hr />
<form action="" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit" class="submit_idea" />
</form>

{% endblock %}

SWIDEA_SITE/swidea/templates/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Idea List</h1>
<p>나의 아이디어를 기록</p>
<br />

<div class="ideas">
	{% for idea in ideas %}

	{% if idea.image %}
	<img src="{{idea.image.url}}" height="220" width="160">
	{% else %}
	<img src="https://picsum.photos/seed/{{idea.id}}/160/220?">
	{% endif %}
	<br />
	<br />

	<h2><a href="{% url 'swidea:idea_detail' idea.id %}">{{idea.title}}</a></h2>
	<hr>
	<h4>예상 개발 툴 : {{idea.devtool}}</h4>
	<h4>아이디어 관심도: <span id="list-interest-{{idea.id}}">{{idea.interest}}</span></h4>

	<div class="interest-btn">
		<button class="increaseQuantity" name="{{idea.id}}"><i class="fas fa-plus"></i></button>
		<button class="decreaseQuantity" name="{{idea.id}}"><i class="fas fa-minus"></i></button>
	</div>

	<br />
	<br />

	<script type="text/javascript">
		var isRun = false;
		$(".increaseQuantity").click(function () {
			if (isRun == true) { return; }
			isRun = true;
			var pk = $(this).attr('name')
			$.ajax({
				type: "POST",
				url: "{% url 'swidea:plus_interest' %}",
				data: { 'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
				dataType: "json",
				success: function (response) {
					$("#list-interest-" + pk).html(response.plus_interest)
					isRun = false;
				},
				error: function (xhr, errmsg, err) {
					console.log('고장');
				}
			});
		})
		$(".decreaseQuantity").click(function () {
			if (isRun == true) { return; }
			isRun = true;
			var pk = $(this).attr('name')
			$.ajax({ // ajax로 서버와 통신
				type: "POST",
				url: "{% url 'swidea:minus_interest' %}",
				data: { 'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
				dataType: "json",
				success: function (response) {
					$("#list-interest-" + pk).html(response.minus_interest)
					isRun = false;
				},
				error: function (xhr, errmsg, err) {
					console.log('고장');
				}
			});
		})
	</script>

	{% endfor%}
</div>

{% endblock %}