piro16_Ajax_Pirostagram/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('main.urls'))
]

piro16_Ajax_Pirostagram/main/urls.py
from django.urls import path 
from . import views

app_name = 'main'

urlpatterns = [
	path('', view = views.post_list, name = 'list'),
	path('create/', view = views.post_create, name = 'create'),
	path('like', views.like, name='like'),
]

piro16_Ajax_Pirostagram/main/models.py
from django.db import models

class Post(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	like = models.IntegerField(default=0)

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
	comment = models.TextField()

piro16_Ajax_Pirostagram/main/forms.py
from django import forms
from .models import *

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = '__all__'

piro16_Ajax_Pirostagram/main/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm

def post_list(request):
	posts = Post.objects.all()
	ctx = {'posts' : posts}
	return render(request, template_name = 'list.html', context = ctx)

def post_create(request):
	if request.method == 'POST':
		form = PostForm(request.POST) 
		if form.is_valid():
			form = form.save()
			return redirect('main:list')
	else:
		form = PostForm() 
		ctx = {'form' : form}
		return render(request, template_name = 'post_form.html', context = ctx)

import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

{% csrf_token %}
@csrf_exempt # Ajax나 CDV?? 사용할때 꼭 써줘야함. 보안무시한다는 의미.
def like_ajax(request):
	req = json.loads(request.body) # 클라이언트에게 받은 {'id':1, 'type':like}를 파이썬 딕셔너리 형태로 저장
	post_id = req['id']
	button_type = req['type']

	print(poist_id, button_type)

	post = Post.objects.get(id=post_id)

	if button_type == 'like':
		post.like += 1
	else:
		post.dislike += 1

	post.save() # 꼭 save해줘야 DB에 저장된다
# 여기까진 바뀐값 DB에 저장만하고 사용자에겐 안 보여줌

# reload없이 바뀐값 알려줌.
# JsonResponse Json형태로 변환
	return JsonResponse({'id':post_id, 'type':button_type}) # 클라이언트에게 응답 {'id':1, 'type':like} 전송 - 화면에 출력

piro16_Ajax_Pirostagram/main/templates/list.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Ajax 실습</title>
</head>

<body>
	<nav><a href="{% url 'main:create' %}">새 글 작성</a></nav>
	<br />

	{% for post in posts %}
	<div>
		<h2>{{post.title}}</h2>
		{{post.content}}
		<button onclick="clickLike({{ post.id }})">좋아요</button>
	</div>
	{% endfor %}

	<script>
		const requestLike = new XMLHttpRequest();

		const clickLike = (id) => {
			const url = "/like/";
			requestLike.open("POST", url, true);
			requestLike.setRequestHeader(
				"Content-Type",
				"application/x-www-form-urlencoded"
			);
			requestLike.send(JSON.stringify({ id: id }));
		};

		const handleLikeResponse = () => {
			if (requestLike.status < 400) { // 에러가 아닌 경우
				const id = JSON.parse(requestLike.response); // Json.parse - 기존 JSON 형태를 자바스크립트에 쓸수있는 형태로 변환
				const element = document.querySelector(`.post-id-${id}`);

				element.innerHTML = "좋아요 누름"
			}
		};

		// requeststate 바뀔 때마다 자동으로 onreadystatechange 함수 호출
		requestLike.onreadystatechange = () => {
			if (requestLike.readyState === XMLHttpRequest.DONE) {
				handleLikeResponse();
			}
		};
	</script>
</body>

</html>

piro16_Ajax_Pirostagram/main/templates/post_form.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">


	<title>글 작성</title>
</head>

<body>
	<form action="" method="POST">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<input type="submit" value="저장" class="submit_post" />
	</form>
</body>

</html>